spring:
  datasource:
    url: jdbc:mysql://localhost:3306/o2odb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  mvc:
    static-path-pattern: /static/**
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_

server:
  servlet:
    context-path: /o2o

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.azzhu.myo2o.entity